project:
  type: website

website:
  title: "Fluconf 2026 indoorco2map"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - abstract.qmd
      - presentation.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



